version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/api
hooks:
  ApplicationStop:
    - location: API/scripts/stop_server.sh
      timeout: 300
  BeforeInstall:
    - location: API/scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: API/scripts/start_server.sh
      timeout: 300
  ApplicationStart:
    - location: API/scripts/start_server.sh
      timeout: 300
  ValidateService:
    - location: API/scripts/validate_service.sh
      timeout: 300
