version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0 # hoặc phiên bản .NET mà bạn đang sử dụng
  pre_build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore repository.sln
  build:
    commands:
      - echo Building the project...
      - dotnet build repository.sln --configuration Release
  post_build:
    commands:
      - echo Running tests...
      - dotnet test repository.sln

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'API/bin/Release/net8.0/publish' # Đường dẫn đến thư mục xuất bản
