name: CI/CD for ASP.NET API

on:
  push:
    branches:
      - main
      - 'releases/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./API.sln
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build ./API.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./API.sln --configuration Release --no-build
  
