name: CI/CD for ASP.NET API

on:
  push:
    branches:
      - main
      - 'releases/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build for Deployment
      run: dotnet publish -c Release -o ./publish

    - name: Zip published files
      run: zip -r deploy.zip ./publish

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{AKIAXM2WGE6ZIWVJNMWK}}
        aws_secret_key: ${{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}}
        application_name: ${{FreshX}}
        environment_name: ${{FreshX-env}}
        version_label: ${{ github.sha }}
        region: ${{us-est-1}}
        zip_file: deploy.zip
